<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
</head>
<body>

<h1>кинцо</h1>

<video controls width="1280" height="720">
  <source src="<?=SITE?>pub/myvideo/films/ded.mp4" type="video/mp4">
</video>  

<audio controls>
    <source src="<?=SITE?>pub/audio/Allegro.mp3" type="audio/mpeg">
</audio>    

</body>    
